# Generated by Django 4.1.1 on 2022-10-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_email_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.CharField(default=True, max_length=70),
            preserve_default=False,
        ),
    ]
