# Generated by Django 4.1.1 on 2022-10-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profile_email_profile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('student', 'student'), ('lecturer', 'lecturer')], default='student', max_length=20, null=True),
        ),
    ]
